/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <nativehelper/jni.h>
/* Header for class com_android_silead_FpAPIFromJNI */

#ifndef _Included_com_android_silead_FpAPIFromJNI
#define _Included_com_android_silead_FpAPIFromJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_silead_fp_utils_FpControllerNative_ENROLL_ERROR
#define com_silead_fp_utils_FpControllerNative_ENROLL_ERROR -1L
#undef com_silead_fp_utils_FpControllerNative_ENROLL_FAIL
#define com_silead_fp_utils_FpControllerNative_ENROLL_FAIL -2L
#undef com_silead_fp_utils_FpControllerNative_ENROLLING
#define com_silead_fp_utils_FpControllerNative_ENROLLING 0L
#undef com_silead_fp_utils_FpControllerNative_ENROLL_SUCCESS
#define com_silead_fp_utils_FpControllerNative_ENROLL_SUCCESS 1L

extern void enrollCredentialRSP (int index, int percent, int result, int area);
extern void identifyCredentialRSP (int index, int result, int fingerid);
extern void fpGenericCB(int index, char* event_name, int result, char* event_data);
extern void slfpkeyRSP (int fpkeyret);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    InitFPSystem
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_InitFPSystem
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    DestoryFPSystem
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_DestoryFPSystem
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    EnrollCredentialREQ
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_android_silead_FpAPIFromJNI_EnrollCredentialREQ
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    EnrollCredentialRSP
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_EnrollCredentialRSP
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    IdentifyCredentialREQ
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_android_silead_FpAPIFromJNI_IdentifyCredentialREQ
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    IdentifyCredentialRSP
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_android_silead_FpAPIFromJNI_IdentifyCredentialRSP
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    RemoveCredential
 * Signature: (I)I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_RemoveCredential
//  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
