/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_silead_FpAPIFromJNI */

#ifndef _Included_com_android_silead_FpAPIFromJNI
#define _Included_com_android_silead_FpAPIFromJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_silead_FpAPIFromJNI_ENROLL_ERROR
#define com_android_silead_FpAPIFromJNI_ENROLL_ERROR -1L
#undef com_android_silead_FpAPIFromJNI_ENROLL_FAIL
#define com_android_silead_FpAPIFromJNI_ENROLL_FAIL -2L
#undef com_android_silead_FpAPIFromJNI_ENROLLING
#define com_android_silead_FpAPIFromJNI_ENROLLING 0L
#undef com_android_silead_FpAPIFromJNI_ENROLL_SUCCESS
#define com_android_silead_FpAPIFromJNI_ENROLL_SUCCESS 1L
/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    InitFPSystem
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_InitFPSystem
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    DestoryFPSystem
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_DestoryFPSystem
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    EnrollCredentialREQ
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_android_silead_FpAPIFromJNI_EnrollCredentialREQ
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    EnrollCredentialRSP
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_EnrollCredentialRSP
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    IdentifyCredentialREQ
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_android_silead_FpAPIFromJNI_IdentifyCredentialREQ
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    IdentifyCredentialRSP
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_android_silead_FpAPIFromJNI_IdentifyCredentialRSP
//  (JNIEnv *, jobject);

/*
 * Class:     com_android_silead_FpAPIFromJNI
 * Method:    RemoveCredential
 * Signature: (I)I
 */
//JNIEXPORT jint JNICALL Java_com_android_silead_FpAPIFromJNI_RemoveCredential
//  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
