/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_lib_led_lib */

#ifndef _Included_jni_lib_led_lib
#define _Included_jni_lib_led_lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_lib_led_lib
 * Method:    setLedStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_1lib_led_1lib_setLedStatus
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
