/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pack_jni_silead_fp */

#ifndef _Included_pack_jni_silead_fp
#define _Included_pack_jni_silead_fp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pack_jni_silead_fp
 * Method:    silead_fp_hwInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_pack_jni_silead_1fp_silead_1fp_1hwInit
  (JNIEnv *, jclass);

/*
 * Class:     pack_jni_silead_fp
 * Method:    silead_fp_DhwInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pack_jni_silead_1fp_silead_1fp_1DhwInit
  (JNIEnv *, jclass);

/*
 * Class:     pack_jni_silead_fp
 * Method:    GetOneFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_pack_jni_silead_1fp_GetOneFrame
  (JNIEnv *, jclass);

/*
 * Class:     pack_jni_silead_fp
 * Method:    writeAddr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pack_jni_silead_1fp_writeAddr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     pack_jni_silead_fp
 * Method:    readAddr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pack_jni_silead_1fp_readAddr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pack_jni_silead_fp
 * Method:    configF0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pack_jni_silead_1fp_configF0
  (JNIEnv *, jclass);

/*
 * Class:     pack_jni_silead_fp
 * Method:    clearIntFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pack_jni_silead_1fp_clearIntFlag
  (JNIEnv *, jclass);

/*
 * Class:     pack_jni_silead_fp
 * Method:    testString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pack_jni_silead_1fp_testString
  (JNIEnv *, jclass);

/*
 * Class:     pack_jni_silead_fp
 * Method:    ReadReg
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pack_jni_silead_1fp_ReadReg
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
